build:
  environment:
    php:
      version: 5.6 # Common versions: 5.4, 5.5, 5.6, 7.0 or hhvm
  tests:
    override:
      -
        command: 'vendor/bin/codecept run --coverage --coverage-xml'
        idle_timeout: 500
        coverage:
          file: 'tests/_output/coverage'
          format: 'php-clover'
filter:
  paths:
    - src/*
    - tests/*
  excluded_paths:
    - tests/_support/*
checks:
  php:
    custom_coding_standard:
      ruleset_path: 'ruleset.xml'
