language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0
    - php: nightly

install:
  - nvm install 0.12
  - npm install -g api-mock
  - composer self-update
  - composer install --no-interaction

before_script:
  # Expand max_nesting_level to prevent error
  - if [[ "$TRAVIS_PHP_VERSION" = "php*" ]]; then echo "xdebug.max_nesting_level=1000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  
  # Add more memory to prevent errors
  - if [[ "$TRAVIS_PHP_VERSION" = "php*" ]]; echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  
  # Start API Mock server
  - api-mock tests/api-blueprint.md > /dev/null 2>&1 &

script:
  - ./vendor/bin/codecept run
  - ./vendor/bin/phpcs --standard=ruleset.xml --extensions=php --ignore=lib --ignore=_data --ignore=_support --ignore=tests src
