language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0
    - php: nightly

before_install:

 # Expand max_nesting_level to prevent error
 - export ADDITIONAL_PATH=`php -i | grep -F --color=never 'Scan this dir for additional .ini files'`
 - echo 'xdebug.max_nesting_level=9999' | sudo tee ${ADDITIONAL_PATH:42}/symfony2.ini

install:
  - nvm install 0.12
  - npm install -g api-mock
  - composer self-update
  - composer install --no-interaction

before_script:
  - api-mock tests/api-blueprint.md > /dev/null 2>&1 &

script:
  - ./vendor/bin/codecept run
  - ./vendor/bin/phpcs --standard=ruleset.xml --extensions=php --ignore=lib --ignore=_data --ignore=_support --ignore=tests src
